### ISSUE TITLE
Nuget package available?

### ISSUE THREAD

**Issue by vde07010702** [munchy-bytes/SchemaMapper#5]
Is there a Nuget package available? I would like to import access mdb database tables to an SQL database and use them from there with SQL commands to import the data to the SQL database. I think this package as a library could  do that.

**Comment by HadiFadl** [comment]
I created a [NuGet package for this project](https://nuget.org/packages/SchemaMapper/), just make sure to install the [Microsoft Access Database Engine](https://www.microsoft.com/en-us/download/details.aspx?id=13255) separately since it cannot be added within package dependencies.

[This class library allows you to import data from multiple sources (including Microsoft Access) tables and store them a unified SQL table](https://github.com/munchy-bytes/SchemaMapper/wiki).

**Comment by vde07010702** [comment]
Thank you very much
-------- Ursprüngliche Nachricht --------Von: Hadi <notifications@github.com> Datum: 14.04.20  01:01  (GMT+01:00) An: munchy-bytes/SchemaMapper <SchemaMapper@noreply.github.com> Cc: vde07010702 <wolfgangsjunkmail@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [munchy-bytes/SchemaMapper] Nuget package available? (#5) 
I created a NuGet package for this project, just make sure to install the Microsoft Access Database Engine separately since it cannot be added within package dependencies.
This class library allows you to import data from multiple sources (including Microsoft Access) tables and store them a unified SQL table.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/munchy-bytes/SchemaMapper/issues/5#issuecomment-613138146",
"url": "https://github.com/munchy-bytes/SchemaMapper/issues/5#issuecomment-613138146",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
